#!/bin/sh

PIDFILE=/run/crossink-supervisor.pid

case "${1:-}" in
	start)
		start-stop-daemon -S -b -m -p "$PIDFILE" --exec /usr/sbin/crossink-supervisor
		;;
	stop)
		start-stop-daemon -K -p "$PIDFILE" -R 2 || true
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}" >&2
		exit 1
		;;
esac
